[package]
name = "dfuse"
version = "0.1.0"
authors = ["Samuel Dolt <samuel@dolt.ch>"]

[dependencies]
byteorder = "0.5.3"
log = "0.3.6"
crc = "1.3.0"
libc = {version = "0.2", optional = true}

[features]
default = []
